### ISSUE TITLE
[FeatureRequest] NPM Package

### ISSUE THREAD

**Issue by EnricoVogt** [dad72/CastorGUI#1]
Could you provide this via npm-registry ?

**Comment by dad72** [comment]
Unfortunately, I don't know how to do this.

**Comment by EnricoVogt** [comment]
https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry

**Comment by dad72** [comment]
I no longer have time to take care of this. I stopped the development of CastorGUI.I No longer maintain it.
