### ISSUE TITLE
Typescript port

### ISSUE THREAD

**Issue by martinlindhe** [dad72/CastorGUI#5]
Hello! I started to port this project into typescript, mostly for learning typescript better..
Would there be any interest in accepting a huge patch that basically reworks the whole project into typescript? The major gains for this would be better IDE integration by providing a d.ts for this project.
Motivation for typescript is because it's interesting and also what Babylon.js is developed in.
Typescript also allows for "decent" autogenerated docs by using for example https://github.com/TypeStrong/typedoc

In order to prove my implemention works I have developed some tests that runs against the current CastorGUI master, and also against my port. I have tried hard not to break compatibility but have made some minor renames of internal variables from french to english names (thank you google translate, i did not know 'police' could mean fontFamily)

I also have found some bugs in the current implementation that has been fixed along the way. If not interested in a typescript port, then maybe bug fixes may be of interest?
I will publish my branch on github in a couple of days probably, and update this issue with a link when it is available.

**Comment by dad72** [comment]
Hello, 

Thank you for your correction work and port to typescript. I am interested in bug fixes and port to typescript, but I also wonder, because I am not very good with this language. If I make changes in javascript, I should also do them in typescript ? I'm afraid not to get there correctly. Would you agree to maintain the version typescript?

Ok for add this port to typescript, because it can be a more for this lib.

Yes, I put some variable in French some times, thank you to fix.

**Comment by martinlindhe** [comment]
Just like with babylon.js, javascript files is generated from the typescript source, so it is no easy way to apply changes directly on the generated javascript files.

Don't worry. All existing javascript is also correct typescript because typescript is a superset of javascript. It is not hugely different.

Sure, I will maintain this port

**Comment by dad72** [comment]
Thank you. Maybe it's time for me to start getting familiar with typescript. I do not think this language is difficult, I'm just a lazy person to learn a new language, but that proves to be useful as you mention it for files. d.ts.

Thanks again for your interest in CastorGUI and for your great contribution.

**Comment by martinlindhe** [comment]
I would recommend trying out Visual Studio Code for the typescript support is spectacular

**Comment by dad72** [comment]
I come to the news about porting to typescript.

**Comment by martinlindhe** [comment]
The port stalled, as some other stuff came up in between. I'll try finish it off, or push the branch of what I have in the next few days.

**Comment by dad72** [comment]
Take your time. I just wanted to know if everything was okay.

Thank you.
