### ISSUE TITLE
Fullscreen error

### ISSUE THREAD

**Issue by michaelilyin** [dad72/CastorGUI#6]
When I trying to switch my scene into fullscreen mode browser redirects current page. 
You can see an example here: http://babylonjs-playground.azurewebsites.net/#1YYAZQ#1

**Comment by dad72** [comment]
This must be a bug from Babylon. It is Babylon who create the fullscreen and who must create this redirects.

Here I remove "false" from switchFullscreen() and you can see that the page requests to be refreshed.

http://babylonjs-playground.azurewebsites.net/#1YYAZQ#2

**Comment by michaelilyin** [comment]
I'm not sure. On my machine page still redirects with your playground. Here I just commented GUI manager initialization and added keypress action for switch into fullscreen: http://babylonjs-playground.azurewebsites.net/#915IF#1 (you need to click anywhere on scene for capture focus and press 'f') and fullscreen switching works well here. I think it is problem in integration castor gui with babylon js. If there is no problems can you prompt some workaround for it?

**Comment by dad72** [comment]
You had reasons. I had a piece of code that came into conflict with Babylon.
I have corrected. Empty the browser caches to test on the playground. It will work.
